#!/usr/bin/env bash
# Installs php versions, theirs extensions and some useful tools
brew update
brew install homebrew/php/php56 homebrew/php/php56-apcu homebrew/php/php56-intl  homebrew/php/php56-mcrypt homebrew/php/php56-memcached homebrew/php/php56-mongodb homebrew/php/php56-opcache homebrew/php/php56-redis homebrew/php/php56-libsodium homebrew/php/php56-twig homebrew/php/php56-uuid homebrew/php/php56-xdebug homebrew/php/php56-yaml
brew install homebrew/php/brew-php-switcher homebrew/php/composer homebrew/php/brew-php-switcher homebrew/php/php-code-sniffer homebrew/php/phpcpd homebrew/php/phpdocumentor homebrew/php/phploc homebrew/php/phpmd homebrew/php/phpmetrics homebrew/php/phpunit homebrew/php/xdebug-osx
brew unlink php56
brew install homebrew/php/php70 homebrew/php/php70-apcu homebrew/php/php70-intl homebrew/php/php70-libsodium homebrew/php/php70-mcrypt homebrew/php/php70-mongodb homebrew/php/php70-opcache homebrew/php/php70-redis homebrew/php/php70-uuid  homebrew/php/php70-xdebug homebrew/php/php70-yaml
brew install --HEAD homebrew/php/php70-memcached
brew unlink php70
brew install homebrew/php/php71 homebrew/php/php71-apcu homebrew/php/php71-intl homebrew/php/php71-libsodium homebrew/php/php71-mcrypt homebrew/php/php71-mongodb homebrew/php/php71-opcache homebrew/php/php71-redis homebrew/php/php71-uuid  homebrew/php/php71-xdebug homebrew/php/php71-yaml